#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo '
-------------------------------------
Big thanks to these projects:

Visit them on www.github.com/
/jlesage/docker-handbrake
/ekim1337/PlexComskip
/erikkaashoek/Comskip
/plexinc/pms-docker
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"
chown abc:abc /config
